[package]
name = "maxhell-as"
version = "0.1.0"
authors = ["Mary <me@thog.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
bit_field = "0.10.1"